import enum


class MessagingChannel(enum.Enum):
    UNKNOWN = 0
    SMS = 1
    VOICE = 2
    USSD = 3
    FB_MESSENGER = 4
    TELEGRAM = 5
    WHATSAPP = 6
    EMAIL = 7


class PaymentChannel(enum.Enum):
    UNKNOWN = 0
    CELLULAR = 1


class MediaType(enum.Enum):
    UNKNOWN = 0
    IMAGE = 1
    AUDIO = 2
    VIDEO = 3
    DOCUMENT = 4
    VOICE = 5
    STICKER = 6
    CONTACT = 7


class VoiceCallDirection(enum.Enum):
    UNKNOWN = 0
    INBOUND = 1
    OUTBOUND = 2


class TextToSpeechVoice(enum.Enum):
    UNKNOWN = 0
    MALE = 1
    FEMALE = 2


class VoiceCallStatus(enum.Enum):
    UNKNOWN = 0
    QUEUED = 100
    ANSWERED = 101
    RINGING = 102
    ACTIVE = 200
    DIALING = 201
    DIAL_COMPLETED = 202
    BRIDGED = 203
    ENQUEUED = 204
    DEQUEUED = 205
    TRANSFERRED = 206
    TRANSFER_COMPLETED = 207
    COMPLETED = 300
    INSUFFICIENT_CREDIT = 400
    NOT_ANSWERED = 401
    INVALID_PHONE_NUMBER = 402
    DESTINATION_NOT_SUPPORTED = 403
    DECOMMISSIONED_CUSTOMER_ID = 404
    EXPIRED = 405
    INVALID_CHANNEL_NUMBER = 406
    APPLICATION_ERROR = 501


class VoiceCallHangupCause(enum.Enum):
    UNKNOWN = 0
    UNALLOCATED_NUMBER = 1
    USER_BUSY = 17
    NORMAL_CLEARING = 16
    NO_USER_RESPONSE = 18
    NO_ANSWER = 19
    SUBSCRIBER_ABSENT = 20
    CALL_REJECTED = 21
    NORMAL_UNSPECIFIED = 31
    NORMAL_TEMPORARY_FAILURE = 41
    SERVICE_UNAVAILABLE = 63
    RECOVERY_ON_TIMER_EXPIRE = 102
    ORIGINATOR_CANCEL = 487
    LOSE_RACE = 502
    USER_NOT_REGISTERED = 606


class PaymentStatus(enum.Enum):
    UNKNOWN = 0
    QUEUED = 100
    PENDING_CONFIRMATION = 101
    PENDING_VALIDATION = 102
    VALIDATED = 103
    INVALID_REQUEST = 200
    NOT_SUPPORTED = 201
    INSUFFICIENT_FUNDS = 202
    APPLICATION_ERROR = 203
    NOT_ALLOWED = 204
    DUPLICATE_REQUEST = 205
    INVALID_PURSE = 206
    INVALID_WALLET = 207
    DECOMMISSIONED_CUSTOMER_ID = 299
    SUCCESS = 300
    PASS_THROUGH = 301
    FAILED = 400
    THROTTLED = 401
    EXPIRED = 402
    REJECTED = 403
    REVERSED = 500
